localdb:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=onboard
    - POSTGRES_PASSWORD=onboard
    - POSTGRES_DB=onboard

testdb:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=onboard_test
    - POSTGRES_PASSWORD=onboard_test
    - POSTGRES_DB=onboard_test